### ISSUE TITLE
Exception while loading entries for entrypoint 'jade' provided by 'toms_trading_network'

### ISSUE THREAD

**Issue by almecho** [tom5454/Toms-Trading-Network#1]
I installed Tom's Trading Network from the Modrinth update that got published overnight, and found the following issue when running it while also running the latest commit of Jade built against -pre5.

```
[23:22:39] [Server thread/INFO]: Start loading plugin from Jade
[23:22:39] [Server thread/INFO]: Start loading plugin from Jade
[23:22:39] [Server thread/INFO]: Start loading plugin from Jade
[23:22:39] [Server thread/INFO]: Start loading plugin from Tom's Trading Network
[23:22:39] [Server thread/ERROR]: Error loading plugin at null
net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'jade' provided by 'toms_trading_network'
        at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:56) ~[fabric-loader-0.14.19.jar:?]
        at snownee.jade.Jade.lambda$loadComplete$6(Jade.java:153) ~[Jade-1.20-fabric-11.0.0.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at snownee.jade.Jade.loadComplete(Jade.java:148) ~[Jade-1.20-fabric-11.0.0.jar:?]
        at snownee.jade.Jade.lambda$onInitialize$5(Jade.java:142) ~[Jade-1.20-fabric-11.0.0.jar:?]
        at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$2(ServerLifecycleEvents.java:49) ~[fabric-lifecycle-events-v1-2.2.1+dcb9d1cab3-5a331a25e7168260.jar:?]
        at net.minecraft.server.MinecraftServer.handler$zfh000$fabric-lifecycle-events-v1$afterSetupServer(MinecraftServer.java:3342) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: net.fabricmc.loader.api.LanguageAdapterException: java.lang.ClassNotFoundException: com.tom.trading.jade.JadePlugin
        at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:52) ~[fabric-loader-0.14.19.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.19.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.19.jar:?]
        ... 9 more
Caused by: java.lang.ClassNotFoundException: com.tom.trading.jade.JadePlugin
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.19.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.19.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.14.19.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.19.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.19.jar:?]

```      
Was rubber ducking in Snownee's Discord but then after looking at it more closely, realized it was probably something on this side causing the log spam.

Could the current version of Jade from Github for -pre5 being version 11.0.0 and TTN for -pre5 being built against the version of Jade currently on CurseForge (jade-324717:4438356 == Jade-1.19.4-fabric-10.0.0.jar) be causing a problem?

**Comment by almecho** [comment]
Oh, I think I might see the issue. It's one of a bunch of plugins currently commented out of build.gradle entirely (presumably due to their respective mods not yet being built for -pre5).

Either that explains why explain why it's not able to access that entrypoint, or I'm still wrong :|
